name: Akif's action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run : echo its first

      - name: Second Step
        run : echo its end
